server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: xxy-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxy_picture?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1111
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000
  profiles:
    active: local

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
x:
  enable: true
  openapi:
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xxy.xxypicturebackend.controller
    title: Xxy-API
    version: 1.0.0

#对象存储配置
cos:
  client:
    host: https://xxy-13890302957-1364108455.cos.ap-chongqing.myqcloud.com
    region: ap-chongqing
    bucket: xxy-13890302957-1364108455