server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: xxy-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xxy_picture?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1111

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    #仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xxy.xxypicturebackend.controller
    title: Xxy-API
    version: 1.0.0

#对象存储配置
#cos:
#  client:
#    host:
#    secretId:
#    secretKey:
#    region:
#    bucket: